### ISSUE TITLE
Create Slack

### ISSUE THREAD

**Issue by mgattozzi** [Alchemist-rs/Alchemist#29]
Create Slack for use among contributors to ask for help etc.

**Comment by TheDoctorsLife** [comment]
This is highly welcomed.

**Comment by mgattozzi** [comment]
I've made it. I can send you an invite if I get your email.

**Comment by TheDoctorsLife** [comment]
hoffmeyer25@gmail.com

**Comment by mgattozzi** [comment]
You should get the invite. Ping me on Slack when you log in.

**Comment by mgattozzi** [comment]
Before closing I'm add instructions to the Readme on getting an invite
